D:\vsts\QRCode\Console\bin\Release\net6.0-windows\QRMake.exe -format="svg.circle" -save="givingps.svg" https://aka.ms/givingps
D:\vsts\QRCode\Console\bin\Release\net6.0-windows\QRMake.exe -format="svg.circle" -save="benevity.svg" https://microsoft.benevity.org/cause/840-912045918
D:\vsts\QRCode\Console\bin\Release\net6.0-windows\QRMake.exe -format="svg.circle" -save="gs25.svg" https://www.puzzyle.net/gs25/Map25.xhtml
D:\vsts\QRCode\Console\bin\Release\net6.0-windows\QRMake.exe -format="svg.circle" -save="Gumball.svg" https://www.puzzyle.net/Posters/Gumball.xhtml?gs25
D:\vsts\QRCode\Console\bin\Release\net6.0-windows\QRMake.exe -format="svg.circle" -save="SpaghettiCode.svg" https://www.puzzyle.net/Posters/SpaghettiCode.xhtml?gs25
D:\vsts\QRCode\Console\bin\Release\net6.0-windows\QRMake.exe -format="svg.circle" -save="EmojiDM.svg" https://www.puzzyle.net/Posters/EmojiDM.xhtml?gs25
D:\vsts\QRCode\Console\bin\Release\net6.0-windows\QRMake.exe -format="svg.circle" -save="Computers.svg" https://www.puzzyle.net/Posters/Computers.xhtml?gs25
D:\vsts\QRCode\Console\bin\Release\net6.0-windows\QRMake.exe -format="svg.circle" -save="GeneticsOfHumor.svg" https://www.puzzyle.net/Posters/GeneticsOfHumor.xhtml?gs25
D:\vsts\QRCode\Console\bin\Release\net6.0-windows\QRMake.exe -format="svg.circle" -save="PaperProducts.svg" https://www.puzzyle.net/Posters/PaperProducts.xhtml?gs25
D:\vsts\QRCode\Console\bin\Release\net6.0-windows\QRMake.exe -format="svg.circle" -save="BillDingSight.svg" https://www.puzzyle.net/Posters/BillDingSight.xhtml?gs25